name: Check for new versions, modify formula and commit

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  modify-and-execute-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Execute JavaScript File
      run: node index.js